### ISSUE TITLE
Check out but can not run

### ISSUE THREAD

**Issue by LiuDeng** [Friend-LGA/LGDrawer#1]
First of all thank you for your great job.
After i check out the project i can not run it.
![2015-07-11 01 49 24 pm](https://cloud.githubusercontent.com/assets/1720312/8632569/be464ba0-27d3-11e5-83e8-cdda3ecc4707.png)

**Comment by Friend-LGA** [comment]
To try demo project you need to install cocoapods dependencies.
- Read and install cocoapods https://cocoapods.org/
- Run 'pod install' in terminal from 'Demo' directory (or just use script 'podsInstall.command')
- Use 'LGDrawerDemo.xcworkspace' not 'LGDrawerDemo.xcodeproj'
